version: '3.8'

services:
  frontend:
    build:
      context: ./challenge-front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:3001

  backend:
    build:
      context: ./challenge-back
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/challenge_db
      - NODE_ENV=production

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=challenge_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
